encdec:
  epoch: 5
  lstm_layers: 2
  dropout: 0.1
  batch: 128
  embed: 256
  hidden: 512
  model: ./resources/testmodel
  max_vocab_size: 5000
train_file:
  q: ./resources/input4.txt
  a: ./resources/output4.txt
train_token_file:
  q: ./resources/inputtoken.txt
  a: ./resources/outputtoken.txt
neologd_dic_path: /data/home/katsumi/mecab/dic/mecab-ipadic-neologd
save_model_path:  ./resources/testmodel